### ISSUE TITLE
Report without diffs causes NullPointerException

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck.cli#129]
If one passes a report without diffs to the CLI, a `NullPointerException` is thrown:

```
$ recheck diff tests.report 
Checking test report in path 'tests.report'.
java.lang.NullPointerException
	at de.retest.recheck.report.TestReportFilter.filter(TestReportFilter.java:69)
	at de.retest.recheck.report.TestReportFilter.filter(TestReportFilter.java:59)
	at de.retest.recheck.report.TestReportFilter.filter(TestReportFilter.java:48)
	at de.retest.recheck.report.TestReportFilter.filter(TestReportFilter.java:39)
	at de.retest.recheck.report.TestReportFilter.filter(TestReportFilter.java:29)
	at de.retest.recheck.cli.subcommands.Diff.run(Diff.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at de.retest.recheck.cli.RecheckCli.main(RecheckCli.java:29)
```

May be a problem with other commands that use `TestReportFilter` too.

**Comment by beatngu13** [comment]
Solved via https://github.com/retest/recheck/pull/422, will be merged with the next recheck release.
